import Navbar from '@/components/layout/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import Providers from '@/lib/providers';

import Script from 'next/script';
import { ReactNode } from 'react';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

const roboto = Roboto({
    subsets: ['latin'],
    variable: '--font-roboto',
    weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${inter.variable} ${roboto.variable}`}>
            <head>
                <script
                    async
                    src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2353524585423199"
                    crossOrigin="anonymous"
                ></script>

            <script
                async
                src="https://fundingchoicesmessages.google.com/i/pub-2353524585423199?ers=1"
                nonce="ocgMTzQ86Oa29qV3SNKsUg"
            ></script>
            
            </head>

            <body>
                <Script
                    src={`https://maps.google.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places&callback=Function.prototype`}
                    strategy={'afterInteractive'}
                />
                <Providers>
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
